kubectl delete deployment logs
kubectl delete deployment rabbitmq
kubectl delete deployment redis
kubectl delete deployment rest-dep
kubectl delete service rest-svc
kubectl delete service rabbitmq
kubectl delete service redis
kubectl delete deployment will-work
kubectl delete ingress rest-ingress
